require "prototypes.entity.replicating-belts"
require "prototypes.item.replicating-belts"
require "prototypes.recipe.replicating-belts"
require "prototypes.technology.replicating-belts"
require "prototypes.input"